### ISSUE TITLE
Singular matrix error when converting wcs to header

### ISSUE THREAD

**Issue by landmanbester** [ratt-ru/pfb-clean#55]
I'm running into the following singular matrix error when converting wcs to header
```
Traceback (most recent call last):
  File "/home/bester/venvs/pfb/bin/pfb", line 33, in <module>
    sys.exit(load_entry_point('pfb-clean', 'console_scripts', 'pfb')())
  File "/home/bester/venvs/pfb/lib/python3.9/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/home/bester/venvs/pfb/lib/python3.9/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/home/bester/venvs/pfb/lib/python3.9/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/bester/venvs/pfb/lib/python3.9/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/bester/venvs/pfb/lib/python3.9/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/home/bester/pfb-clean/pfb/workers/grid.py", line 75, in grid
    return _grid(**opts)
  File "/home/bester/pfb-clean/pfb/workers/grid.py", line 392, in _grid
    hdr = set_wcs(cell_size / 3600, cell_size / 3600,
  File "/home/bester/pfb-clean/pfb/utils/fits.py", line 64, in set_wcs
    header = w.to_header()
  File "/home/bester/venvs/pfb/lib/python3.9/site-packages/astropy/wcs/wcs.py", line 2670, in to_header
    header_string = self.wcs.to_header(relax)
astropy.wcs._wcs.SingularMatrixError: ERROR 3 in wcsset() at line 2739 of file cextern/wcslib/C/wcs.c:
Linear transformation matrix is singular.
ERROR 3 in linset() at line 674 of file cextern/wcslib/C/lin.c:
PCi_ja matrix is singular.
```
This only seems to happen some of the time, if I go through exactly the same steps in an ipython session I can't reproduce the error. Anyone perhaps know what could be causing this? Tagging @o-smirnov @JSKenyon @bennahugo

**Comment by landmanbester** [comment]
Quite simply trying to set up a WCS and convert to a hdr using https://github.com/ratt-ru/pfb-clean/blob/57b4b74a345964f3d7316f41f35714d5c8e99998/pfb/utils/fits.py#L28

The confusing part is that I can't reproduce it with the same arguments running an interactive ipython session, it happens every now and then when I run the [grid](https://github.com/ratt-ru/pfb-clean/blob/stimelator/pfb/workers/grid.py) worker

**Comment by bennahugo** [comment]
Odd I can't see anything wrong here.  So you are saying that it is
non-deterministic when run with precisely the same parameters?

**Comment by landmanbester** [comment]
It would seem that way. It's only happened to me twice. I'm trying to reproduce it but it refuses to reproduce. I've added a try except so it can drop me into the debugger when it happens again
