### ISSUE TITLE
BMAJ keyword error (simple_spi_fitter.py)

### ISSUE THREAD

**Issue by IanHeywood** [ratt-ru/pfb-clean#6]
It seems to be looking for BMAJ in the header of the model file (which generally won't have beam keywords):

```
$ python simple_spi_fitter.py --psf-pars 0.002334299492444396 0.001883134708575069 -11.20665826780242 -ncpu 72 -maxDR 1e-7 -o spitest -model modelcube_pbcor.fits


Input Options:
model  =  modelcube_pbcor.fits
residual  =  None
output_filename  =  spitest
psf_pars  =  [0.002334299492444396, 0.001883134708575069, -11.20665826780242]
circ_psf  =  False
threshold  =  5
maxDR  =  1e-07
ncpu  =  72
beam_model  =  None
pb_min  =  0.05
products  =  aeikIbcm
padding_frac  =  0.2
dont_convolve  =  False
channel_weights  =  None
ref_freq  =  None


Using 72 threads


Using emaj = 2.33e-03, emin = 1.88e-03, PA = -1.12e+01

Cube frequencies:
[9.09e+08 1.02e+09 1.12e+09 1.23e+09 1.34e+09 1.44e+09 1.55e+09 1.66e+09]
Reference frequency is 9.09e+08 Hz

Traceback (most recent call last):
  File "simple_spi_fitter.py", line 368, in <module>
    main(args)
  File "simple_spi_fitter.py", line 162, in main
    new_hdr = set_header_info(mhdr, ref_freq, freq_axis, args, beampars)
  File "/home/ianh/Software/codex-africanus/africanus/model/spi/examples/utils.py", line 57, in set_header_info
    new_hdr[key] = mhdr[key]
  File "/home/ianh/venv/codex/lib/python3.6/site-packages/astropy/io/fits/header.py", line 148, in __getitem__
    card = self._cards[self._cardindex(key)]
  File "/home/ianh/venv/codex/lib/python3.6/site-packages/astropy/io/fits/header.py", line 1708, in _cardindex
    raise KeyError(f"Keyword {keyword!r} not found.")
KeyError: "Keyword 'BMAJ' not found."
```

**Comment by landmanbester** [comment]
Hmmm, that happens when I to copy the old header info. I have assumed that the header has the same keywords as those found in wsclean's headers. I've modified it to only copy global keys which I have taken to be

['SIMPLE', 'BITPIX', 'NAXIS', 'NAXIS1', 'NAXIS2', 'NAXIS3',
 'NAXIS4', 'CTYPE1', 'CTYPE2', 'CTYPE3', 'CTYPE4', 'CRPIX1',
 'CRPIX2', 'CRPIX3', 'CRPIX4', 'CRVAL1', 'CRVAL2', 'CRVAL3',
 'CRVAL4', 'CDELT1', 'CDELT2', 'CDELT3', 'CDELT4', 'CUNIT1',
 'CUNIT2', 'CUNIT3', 'CUNIT4']

Note this function is in africanus so you need to pull my split_spi_funcs branch. If you are happy to use the version in this repo I can move all the functionality over. Let me know when you make the switch, or if you run into more issues
